### ISSUE TITLE
Error: no_grad.__init__() takes 1 positional argument but 2 were given, on Ubuntu 22.04

### ISSUE THREAD

**Issue by ekorudi** [tysam-code/hlb-gpt#14]
```
hlb-gpt$ python3 main.py 
Traceback (most recent call last):
  File "/ok/dev/ML/hlb-gpt/main.py", line 271, in <module>
    def get_batch(data_dict, key, batchsize, length):
TypeError: no_grad.__init__() takes 1 positional argument but 2 were given

$ python -V
Python 3.10.12
```

**Comment by tysam-code** [comment]
Hi! I don't know if I can do a lot of environment debugging, this looks like a requirements issue and not a code bug. I tested this codebase on, PyTorch 2.1 it is, I believe? You may need to upgrade, this looks like the no_grad decorator is the same between 2.1 and 2.2.

Thanks!

**Comment by snimu** [comment]
If this is on Lambda, their PyTorch is screwed right now. 

Just run `pip install -U torch` before doing anything else.

Otherwise, `nn.LayerNorm` won't have a `bias` parameter, and other stupid things, in addition to the `no_grad` thing.
